### ISSUE TITLE
「Explore More ⇩」をクリックしても何も起きない

### ISSUE THREAD

**Issue by haruhisa-enomoto** [lean-ja/lean-ja.github.io#14]
環境に依存するかもしれませんが、デスクトップPCでChromeで表示すると「Explore More ⇩」というものが表示されて、クリックすると下にジャンプすることが期待されますが、クリックしても何も起きません。
仕様でしょうか？

**Comment by Seasawher** [comment]
それは多分　juice の仕様ですね

**Comment by Seasawher** [comment]
template/index.html でボタンを上書きしていますが、juice テーマのコードそのままにしてあるので、多分 juice の仕様です。
したがってクローズします。

ただし、きちんと確認したわけではないので、juice テーマの公式ページでのボタンの仕様と比較して、違うようなら再オープンしてください。

**Comment by haruhisa-enomoto** [comment]
ありがとうございます。
いくつかJuiceテーマのページを見てみましたが、[公式のデモ](https://juice.huhu.io/)ではExpand Moreをクリックすると下にジャンプするみたいです。showcasesのいくつかのページでも（例えば[arara](https://islandoftex.gitlab.io/arara/)等）機能しているみたいです（ただ機能していないページもありました）。
中身を見てみると、idが"feature"なdivが無いことが原因のようです（公式デモでの「Overview」がそれみたいです）。
修正するプルリクを出すことにします。
