### ISSUE TITLE
lean-ja内の日本語訳ページへのリンク追加

### ISSUE THREAD

**Issue by s-taiga** [lean-ja/lean-ja.github.io#30]
下記の本について翻訳が完了・ほぼ終わっていることもあるのでlean-jaのリンクページに追加できればと考えております。
* Functional Programming in Lean(https://lean-ja.github.io/fp-lean-ja/)
* Mathematics in Lean(https://lean-ja.github.io/mathematics_in_lean_source/)
* Metaprogramming in Lean(https://lean-ja.github.io/lean4-metaprogramming-book-ja/)

**Comment by Seasawher** [comment]
翻訳を確認しましたが、誤訳や日本語としておかしい文章が散見されるため修正を待つことにします。
