### ISSUE TITLE
ディスコード追加

### ISSUE THREAD

**Issue by Seasawher** [lean-ja/lean-ja.github.io#8]
ディスコードサーバをリンク集に追加し，lean のためのサーバではないことを注意する

**Comment by aconite-ac** [comment]
自分も同感で、lean-jaからはリンクせず、
ディスコードサーバーのガイドラインに書かれている
> 招待したい人がいたら各自招待リンクを生成して招待する

に従うのがより自然に思えます。

**Comment by Seasawher** [comment]
ではいったんこの案は凍結しましょうか
